services:
  companyname.api:
    image: ${DOCKER_REGISTRY-}companynameapi
    container_name: CompanyName.Api
    build:
      context: .
      dockerfile: src/API/CompanyName.Api/CompanyName.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  companyname.database:
    image: postgres:17
    container_name: CompanyName.Database
    environment:
      - POSTGRES_DB=CompanyName
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  companyname.identity:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: CompanyName.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
      - 9000:9000
    user: root # Required to set volume permissions

  companyname.seq:
    image: datalust/seq:2025.2
    container_name: CompanyName.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true # local dev only
    ports:
      - 5341:5341
      - 8081:80

  companyname.redis:
    image: redis:latest
    container_name: CompanyName.Redis
    restart: always
    ports:
      - 6379:6379

  companyname.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: CompanyName.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
